# Generated by Django 6.0.4 on 2026-08-03 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_email_case_insensitive_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_two_factor_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='totp_secret',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
